
title: Yalun (Aaron) Wu


#sidebar links
email: wuyalun1 [at] bjtu.edu.cn
#phone: 012 345 6789
#linkedin: 
# website_zhihu: ZHIHU
#website_csdn: CSDN
website_google: Google Scholar
github: Github
my_cv: CV
port: 4001
#Update all the sections by editing the files inside _includes folder.

theme: jekyll-theme-cayman
